# Generated by Django 5.1.3 on 2024-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0010_alter_property_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, choices=[('Керчь', 'Керчь'), ('Феодосия', 'Феодосия'), ('Симферополь', 'Симферополь')], default='', max_length=25, verbose_name='Город'),
        ),
    ]
