# Generated by Django 5.1.3 on 2024-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0011_alter_property_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='adress',
            field=models.CharField(default='', max_length=200, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
