# Generated by Django 5.1.3 on 2024-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0012_remove_property_name_property_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='Фото'),
        ),
    ]
