# Generated by Django 5.1.3 on 2024-11-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0013_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rieltor.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Город'),
        ),
    ]
