# Generated by Django 5.1.3 on 2024-11-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0018_faq_alter_property_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
    ]
