# Generated by Django 5.1.3 on 2024-11-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0022_rename_property_propertyimage_propertys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='propertys',
            new_name='property',
        ),
    ]
