# Generated by Django 5.1.3 on 2024-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0023_rename_propertys_propertyimage_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(blank=True, default='Договорная', max_length=255, null=True, verbose_name='Цена'),
        ),
    ]
